---
title: "Artefact Date Elicitation Report"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "`r format(Sys.time(), '%d %B %Y, %H:%M')`"
fontsize: 11pt
params:
  fit: NA
  bin.left: NA
  bin.right: NA
  chips: NA
  roulette: NA
  ql: NA
  qu: NA
  xl: NA
  xu: NA
  xlab: NA
  nBins: NA
  fs: NA
  xLable: NA
  startDate: NA
  endDate: NA
  ybreaks: NA
  QoI: NA
  TS: NA
  TE: NA
  selected_distribution: NA
  feedback: NA
  fq: NA
  fp: NA
  user_notes: NA
  expert: NA,
  facilitator: NA,
  findtype: NA,
  EoI: NA,
  UFI: NA,
  ULI: NA,
  USI: NA
  PoE: NA
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,
                      fig.pos = 'h',
                      fig.align = 'center',
                      fig.height = 6.5,
                      fig.width = 4.5,
                      dpi =150)

if (knitr::is_latex_output()) {
  theme_set(
    theme_bw(base_size = 9) +
      theme(
        panel.grid = element_blank(),
        axis.line = element_line(linewidth = 0.3)
      )
  )
}
showplots <- FALSE
```




```{r, echo = FALSE}
fit <- params$fit
bin.left <- params$bin.left
bin.right <- params$bin.right
chips <- params$chips
roulette <- params$roulette
ql <- params$ql 
qu <- params$qu
xl <- params$xl
xu <- params$xu 
fs <- params$fs
xLabel <- params$xLabel
startDate <- params$startDate
endDate <- params$endDate
nBins <- params$nBins
ybreaks <- params$ybreaks
QoI <- params$QoI
TS <- params$TS
TE <- params$TE
selected_distribution <- params$selected_distribution
filename <- system.file(
  "shiny", "elicitation_app", "distributionsChild.Rmd",
  package = "spade")
feedback<- params$feedback
fq<-params$fq
fp<-params$fp
user_notes = params$user_notes
expert = params$expert
faciliator = params$facilitator
findtype= params$findtype
EoI= params$EoI
UFI = params$UFI
ULI = params$ULI
USI = params$USI
PoE = params$PoE
```

**Expert**: `r expert`  
**Facilitator**: `r faciliator`  
**Find Type**: `r findtype`  
**Event of Interest**: `r EoI`  
**Unique Find Identifier**: `r UFI`  
**Unique Location Identifier**: `r ULI`  
**Unique Site Identifier**: `r USI`  
**Portfolio of Evidence**: `r PoE`  


```{r child=filename}
```

This report was generated by the SPADE elicitation app available in the SPADE package.
